Align with master (#108)
* Fix nmo format (#57)

* Update KubeVirt and it's dependencies (#60)

Signed-off-by: Lev Veyde <lveyde@redhat.com>

* Update converged manifests (#61)

Signed-off-by: Lev Veyde <lveyde@redhat.com>

* Bump cdi to version v0.18.0 (#62)

* Bump the web-ui to 0.1.4 and regenerate manifests (#63)

* Bump ssp to 1.0.0 and update CSV (#64)

* Add Web-UI scheme registration code (#65)

Signed-off-by: Lev Veyde <lveyde@redhat.com>

* ssp-operator: update manifests to export POD_NAME (#69)

This environment variable is needed to run
the SSP operator on top of ansible-operator >= 0.4

Signed-off-by: Francesco Romani <fromani@redhat.com>

*  Gopkg.toml: Bump web-ui-operator v0.1.5  (#68)

* Gopkg.toml: Bump web-ui-operator v0.1.5

* dep ensure for web-ui-operator v0.1.5

* web-ui: let operator set the registry and tag (#58)

* web-ui: let operator set the registry and tag

* Add WebuiContainerPrefix

* web-ui: update by ./hack/build-manifests.sh

* Add compiled binary back into tree (#71)

* Instead of GETing resources, always attempt to CREATE them (#73)

* Web ui operator v0.1.6 (#75)

* Bump web-ui-operator v0.1.6

* dep ensure for web-ui-operator v0.1.6

* hack/build-manifests.sh after web-ui-operator-v0.1.6

* Bump cdi to version v1.9.0 (#77)

* Fixed cluster_role manifest (#78)

When applying the manifests, one gets the following error:

error: error validating "deploy/converged/cluster_role.yaml": error
validating data: ValidationError(ClusterRole.rules[9]): unknown field
"resourceName" in io.k8s.api.rbac.v1.PolicyRule; if you choose to ignore
these errors, turn validation off with --validate=false

The right name for the attribute is resourceNames (plural).

Fixes #67

* Update Kubevirt to v0.17.0 (#80)

* Update KubeVirt to v0.17.0

Signed-off-by: Marc Sluiter <msluiter@redhat.com>

* Fix k8s client-go version mismatch...

Signed-off-by: Marc Sluiter <msluiter@redhat.com>

* Rebuilt manifests

Signed-off-by: Marc Sluiter <msluiter@redhat.com>

* Web ui operator v0.1.8 (#83)

* Bump web-ui-operator v0.1.8

* dep ensure for web-ui-operator-v0.1.8

* hack/build-manifests.sh after web-ui-operator-v0.1.8

* web-ui: hardcode "Version: automatic" (#82)

to enforce automatic web-ui version selection.

More info: https://github.com/kubevirt/web-ui-operator/pull/72

* Follow up #80 with update to hack script (#84)

* cna 0.7.0 (#85)

* bump cna to 0.7.0

Signed-off-by: Petr Horacek <phoracek@redhat.com>

* take default cna images from cna sources

Instead of keeping duplicates of default CNA component images under
hack/defaults, use whatever CNA provides and only overwrite that if
explicitly asked to.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

* add bridge marker component to CNA

This image is deployed as a part of linuxBridge component.

Signed-off-by: Petr Horacek <phoracek@redhat.com>

* Web ui operator v0.1.10 (#88)

* Bump web-ui-operator-v0.1.10

* dep ensure for web-ui-operator-v0.1.10

* hack/build-manifests.sh after web-ui-operator-v0.1.10

* Enable CPU feature discovery for kubevirt (#89)

This patch enables the CPUNodeDiscovery feature gate that enables cpu model and feature based scheduling in kubevirt.

* Rebuild the binary (#90)

* SSP: update operator APIs to 1.0.1 (#91)

Resolves: https://bugzilla.redhat.com/1709268
Signed-off-by: Francesco Romani <fromani@redhat.com>

* Rebuild the binary (#92)

* SSP: don't specify component versions (#94)

Just request the sub-components presence and let the operator
decide which version should be pulled.

Bug-Url: https://bugzilla.redhat.com/1710333
Signed-off-by: Francesco Romani <fromani@redhat.com>

* Add basic ci (#95)

* Add build target

* Add basic travis script

* Fix hco build

* Rebuild committed binary

*     * Vendor cdi related csv methods from cdi v1.9.1 (#97)

* Bump cdi version to v1.9.1

* Add Node Maintenance CRD (#96)

* Add node maintenance CRD to templates

Fixes #86

* Address client-go version mismatch

* Update README to include nodemaintenance CRD

* SSP: watch all the namespaces (#98)

* ssp: templates: set operator to watch all ns

Not just the namespace on which the operator is going to run.
For more info, see:
https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md

Signed-off-by: Francesco Romani <fromani@redhat.com>

* deploy: converged: re-run hack/build-manifests.sh

Signed-off-by: Francesco Romani <fromani@redhat.com>

* ssp-op: update watched namespaces

Signed-off-by: Francesco Romani <fromani@redhat.com>

* Align NMO to version v0.3.0 (#101)

* Add the abilty to build and test on a local cluster (#87)

- Add new targets to the makefile for building and testing
- Change the container image to ubi8-minimal

Signed-off-by: Ido Rosenzwig <irosenzw@redhat.com>